### ISSUE TITLE
Fail to install ricty

### ISSUE THREAD

**Issue by tingfangyeh** [sanemat/homebrew-font#54]
After typing this as below in the terminal of Mac
`% brew install ricty`
It came out the message as below and failed to install the font "Ricty"
```
./ricty_generator-4.1.1.sh: line 1096: 48726 Abort trap: 6           $fontforge_command -script ${tmpdir}/${modified_inconsolata_generator} 2> $redirection_stderr
Remove temporary files
Abnormally terminated
```
Is there any solution?

**Comment by equal-l2** [comment]
I cannot reproduce your problem unfortunately.
Have you tried [general troubleshooting process for Homebrew](https://docs.brew.sh/Troubleshooting)?

**Comment by tingfangyeh** [comment]
I tried to troubleshoot and also try `brew doctor`
It said it is ok but I still cannot install the ricty via Homebrew :(

I am not sure whether the problem is similar with this issue as below or not.
https://github.com/sanemat/homebrew-font/issues/51

**Comment by equal-l2** [comment]
I think #51 is not relevant, as it was a kind of network error.

Could you provide me the output of `brew config`, to know your environment?

**Comment by tingfangyeh** [comment]
Thank you for your reply.
The output of `brew config` is as below. 
```
yoshi@Yoshis-MacBook-Pro-15-2019 ~ % brew config
HOMEBREW_VERSION: 2.5.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: abf214c01ff1edb57acf7e23d5eb24a777335e11
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: fe68a799384d57429b368ec0363877a4458927fd
Core tap last commit: 5 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.5MKlDriPqc/org.macosforge.xquartz:0
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 12.0 build 1200
Git: 2.28.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.7-x86_64
CLT: 12.0.0.0.1.1599194153
Xcode: N/A
XQuartz: 2.7.11 => /opt/X11
```

**Comment by tingfangyeh** [comment]
By the way, the output of `brew install ricty` is as below.
This thread comes out at the end lol

```
yoshi@Yoshis-MacBook-Pro-15-2019 ~ % brew install ricty
==> Installing ricty from sanemat/font
==> Downloading https://github.com/google/fonts/raw/f0e90b27b6e567af9378952a37bc8cf29e2d88e9/ofl/inconsolata/Inconsolata-
Already downloaded: /Users/yoshi/Library/Caches/Homebrew/downloads/24a8808bea96ca8579bc893547b86241448b2944cca2414aca6d6400986529a3--Inconsolata-Regular.ttf
==> Downloading https://github.com/google/fonts/raw/f0e90b27b6e567af9378952a37bc8cf29e2d88e9/ofl/inconsolata/Inconsolata-
Already downloaded: /Users/yoshi/Library/Caches/Homebrew/downloads/0f8e8be9545eb996c487dc08e9d95b408e9b5d0084889938d588d7bf7c98c31f--Inconsolata-Bold.ttf
==> Downloading https://osdn.net/frs/redir.php?m=gigenet&f=mix-mplus-ipa%2F72511%2Fmigu-1m-20200307.zip
Already downloaded: /Users/yoshi/Library/Caches/Homebrew/downloads/714dbd55b1dcf9c8ad1a062e449903a44ae84733378f487fe6c2df1478b8ab90--migu-1m-20200307.zip
==> Downloading https://raw.githubusercontent.com/rictyfonts/rictyfonts.github.io/master/files/ricty_generator-4.1.1.sh
Already downloaded: /Users/yoshi/Library/Caches/Homebrew/downloads/cb99034257f3d03c0da16d401031035d690fa8c7a28b1524ba3c9c2ddd35608c--ricty_generator-4.1.1.sh
==> sh ./ricty_generator-4.1.1.sh Inconsolata-Regular.ttf Inconsolata-Bold.ttf migu-1m-regular.ttf migu-1m-bold.ttf
Last 15 lines from /Users/yoshi/Library/Logs/Homebrew/ricty/01.sh:
migu-1m-bold.ttf

Ricty Generator 4.1.1

Copyright (c) 2011-2017 Yasunori Yusa
All rights reserved.

This script is to generate Ricty font from Inconsolata and Migu 1M.
The generated fonts are licensed by both SIL Open Font License (OFL)
Version 1.1 and IPA Font License Agreement v1.0.
Due to OFL 1.1 Section 5, it is PROHIBITED to distribute the generated fonts.

./ricty_generator-4.1.1.sh: line 1096:  4798 Abort trap: 6           $fontforge_command -script ${tmpdir}/${modified_inconsolata_generator} 2> $redirection_stderr
Remove temporary files
Abnormally terminated

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/sanemat/homebrew-font/issues

These open issues may also help:
Fail to install ricty https://github.com/sanemat/homebrew-font/issues/54
```

**Comment by equal-l2** [comment]
Is `brew test fontforge` passes on your env?
If not, this is definitely a fontforge bug and Homebrew folks should handle it.

**Comment by tingfangyeh** [comment]
I tried `brew test fontforge ` and it failed.
How can I fix it?

I tried to install fontforge manually and it did appear in the list of Luanchpad.
However, it doesn't work at all :(

```
yoshi@Yoshis-MacBook-Pro-15-2019 ~ % brew test fontforge
==> Testing fontforge
==> /usr/local/Cellar/fontforge/20200314_1/bin/fontforge -version
Last 15 lines from /Users/yoshi/Library/Logs/Homebrew/fontforge/test.01.fontforge:
2020-10-16 12:16:22 +0900

/usr/local/Cellar/fontforge/20200314_1/bin/fontforge
-version

dyld: Library not loaded: /usr/local/opt/readline/lib/libreadline.8.dylib
  Referenced from: /usr/local/Cellar/fontforge/20200314_1/bin/fontforge
  Reason: image not found
Error: fontforge: failed
An exception occurred within a child process:
  BuildError: Failed executing: /usr/local/Cellar/fontforge/20200314_1/bin/fontforge -version
/usr/local/Homebrew/Library/Homebrew/formula.rb:2032:in `block in system'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1970:in `open'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1970:in `system'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/fontforge.rb:70:in `block in <class:Fontforge>'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1841:in `block (3 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/utils.rb:496:in `with_env'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1840:in `block (2 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/formula.rb:900:in `with_logging'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1839:in `block in run_test'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `block in run'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `chdir'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `run'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2081:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1833:in `run_test'
/usr/local/Homebrew/Library/Homebrew/test.rb:42:in `block in <main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `block in catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:108:in `timeout'
/usr/local/Homebrew/Library/Homebrew/test.rb:41:in `<main>'
```

**Comment by equal-l2** [comment]
It seems something is wrong with your installation of fontforge.
Try `brew reinstall fontforge` and run `brew test fontforge` again.

**Comment by tingfangyeh** [comment]
I tried `brew reinstall fontforge` and ran `brew test fontforge` again,
but it still comes out the same failure as [this](https://github.com/sanemat/homebrew-font/issues/54#issuecomment-709707266) :(

**Comment by equal-l2** [comment]
If so, I think that this is out of my hands unfortunately.
Please report to https://github.com/homebrew/homebrew-core and ask how to fix the test failure first.
If ricty still fails to install after the test has fixed, report again to us.
